import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Blog Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' m-auto p-5'>

       {/* <div className='mx-auto block'  >
            <Image
                  src='/images/travel1.jpg'
                  alt='travel cover photo'
                  width={400}
                  height={300} 
                  className='rounded-tr-lg rounded-tl-lg'
              /> 
              <div className='bg-white p-8 rounded-bl-lg rounded-br-lg w-40'>

              </div>  

      </div>  */} 
        
       <div className='block'>
        
        <div >            
          <Link  href='/forms/createForm'>
           <button className='bg-gray-400 p-2 mt-2'> CREATE FORM </button> 
            </Link>
        </div>  

        <div>
          <Link href='/forms/viewForms'>
          <button className='bg-gray-400 p-2 mt-2'> VIEW FORMS </button> 
          </Link>
        </div>

        <div>
          <Link href='/formList'>
          <button className='bg-gray-400 p-2 mt-2'> VIEW RESPONSE </button> 
          </Link>
        </div>

        <div>
          <Link href='/forms/answerForm'>
          <button className='bg-gray-400 p-2 mt-2'> ANSWER FORM </button> 
          </Link>
        </div>
    
        </div> 
        
      </main>

      <footer className=''>
      
      </footer>
    </div>
  )
}
