import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Blog Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' m-auto p-5'>

       <div className='block'>
        
        <div >            
          <Link  href='/forms/createForm'>
           <button className='bg-gray-400 p-2 mt-2'> CREATE FORM </button> 
            </Link>
        </div>  

        <div>
          <Link href='/forms/viewForms' >
            <button className='bg-gray-400 p-2 mt-2'> VIEW FORM LIST  </button> 
          </Link>
        </div>

        <div>
          <Link href='/forms/answerForm'>
          <button className='bg-gray-400 p-2 mt-2'> ANSWER FORM </button> 
          </Link>
        </div>

        <div>
          <Link href='/forms/viewResult'>
          <button className='bg-gray-400 p-2 mt-2'> VIEW RESULT</button> 
          </Link>
        </div>
    
        </div> 
        
      </main>

      <footer className=''>
      
      </footer>
    </div>
  )
}
